project:
  name: qs-workshop
  regions:
  - us-east-1
  - us-west-2
  - eu-central-1
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-west-1
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: email@yourdomain.com
      KeyPairName: ~/qsworkshop.pem
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "qs-workshop/"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "$[taskcat_current_region]"
